### ISSUE TITLE
最新的蚁剑连接失败

### ISSUE THREAD

**Issue by TryA9ain** [pureqh/webshell#3]
![image](https://user-images.githubusercontent.com/51145610/116799594-53a2fa80-ab2d-11eb-9035-7e69fa400fb4.png)
师傅，最新的蚁剑连接提示返回数据为空
![image](https://user-images.githubusercontent.com/51145610/116799731-759c7d00-ab2d-11eb-97e5-b8f75eaff18e.png)

**Comment by pureqh** [comment]
连接密码是zero 不是pureqh




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pureqh/webshell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 上午10:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pureqh/webshell] 最新的蚁剑连接失败 (#3)





 

 师傅，最新的蚁剑连接提示返回数据为空

**Comment by TryA9ain** [comment]
> 连接密码是zero 不是pureqh
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pureqh/webshell" ***@***.***&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 上午10:02 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[pureqh/webshell] 最新的蚁剑连接失败 (#3) 师傅，最新的蚁剑连接提示返回数据为空 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一样的，我试过了，还是返回数据为空
![image](https://user-images.githubusercontent.com/51145610/116858526-158eff00-ac31-11eb-95e6-e07028d141df.png)

**Comment by pureqh** [comment]
用的是php_webshell.py这个生成器吗&nbsp; 是的话get需要加?pass=pureqh




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pureqh/webshell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pureqh/webshell] 最新的蚁剑连接失败 (#3)





  
连接密码是zero 不是pureqh
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pureqh/webshell" @.&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 上午10:02 @.&gt;; @.***&gt;; 主题:&nbsp;[pureqh/webshell] 最新的蚁剑连接失败 (#3) 师傅，最新的蚁剑连接提示返回数据为空 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
一样的，我试过了，还是返回数据为空

**Comment by TryA9ain** [comment]
> 用的是php_webshell.py这个生成器吗&nbsp; 是的话get需要加?pass=pureqh
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pureqh/webshell" ***@***.***&gt;; 发送时间:&nbsp;2021年5月3日(星期一) 下午5:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [pureqh/webshell] 最新的蚁剑连接失败 (#3) 连接密码是zero 不是pureqh … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pureqh/webshell" @.&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 上午10:02 @.&gt;; @.***&gt;; 主题:&nbsp;[pureqh/webshell] 最新的蚁剑连接失败 (#3) 师傅，最新的蚁剑连接提示返回数据为空 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 一样的，我试过了，还是返回数据为空 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哦，我的，可以了

**Comment by 1ongtoc** [comment]
连接成功后报错{}怎么办
